### PR TITLE
Fix ToString for AWS KMS to include role, context, and profile

### LINKED ISSUE #1580: Add second `kms` list entry when SOPS file created
Hi folks. My approach to allowing users to create secrets, and then for CI to decrypt and use those secrets, is to allow users to create encrypted files using the `sops` CLI.

Users are auth'd using AWS SSO with an AWS CLI profile called `development`.

My creation rules in `.sops.yaml` look like this:

```yaml
creation_rules:
    - kms: arn:aws:kms:us-east-1:123456789123:alias/sops-kms-key
      aws_profile: development
```

So when the encrypted file (say, `secrets.yaml`) is created, it looks like this:

```yaml
username: ENC[...]
password: ENC[...]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:123456789123:alias/sops-kms-key
          created_at: "1970-01-01T00:00:00Z"
          enc: ABCDEF
          aws_profile: development
```

This is great, but I also need my CI system to decrypt these files. The CI server has an AWS IAM role attached (let's call it `CIServerRole`) with permissions to access the KMS key. My solution at the moment is to manually add another `kms` list entry like this:

```diff
[...]
sops:
    kms:
        - arn: arn:aws:kms:us-east-1:123456789123:alias/sops-kms-key
          created_at: "1970-01-01T00:00:00Z"
          enc: ABCDEF
          aws_profile: development
+       # Added manually after file has been encrypted.
+       - arn: arn:aws:kms:us-east-1:123456789123:alias/sops-kms-key
+         created_at: "1970-01-01T00:00:00Z"
+         enc: ABCDEF
+         aws_profile: ""
+         role: arn:aws:iam::123456789123:role/CIServerRole
```

I then commit and push this, and the CI server can happily decrypt the file using that IAM role.

I'd rather avoid having to add this manually, due to the toil and possibility of human error. I'd like the `sops` CLI to automatically populate this second "use a role, not a profile" entry to the `kms` list. Is this possible using `.sops.yaml`?

Thanks, and hugely appreciate the awesome work on SOPS!

Aaron

### PR DESCRIPTION
**Pull request by felixfontein**
Follow-up for #1493, in particular https://github.com/getsops/sops/pull/1493#discussion_r1625318840. Turns out the other fields were important as well.

This not only applies to #1493, but also other operations where `kms.ToString` is used, for example the `rotate` subcommand, the `updatekeys` subcommand, and the `publish` subcommand (the two latter use `DiffKeyGroups`, which relies on `ToString` to identify a full key).

Fixes #1580.

### CODE REVIEW

File: config/config_test.go [hunk 1]
```diff
@@ -538,9 +553,10 @@ func TestKeyGroupsForFileWithGroups(t *testing.T) {
 	conf, err := parseCreationRuleForFile(parseConfigFile(sampleConfigWithGroups, t), "/conf/path", "whatever", nil)
 	assert.Nil(t, err)
 	assert.Equal(t, "bar", conf.KeyGroups[0][0].ToString())
-	assert.Equal(t, "foo", conf.KeyGroups[0][1].ToString())
+	assert.Equal(t, "foo||bar", conf.KeyGroups[0][1].ToString())
+	assert.Equal(t, "foo|baz:bam", conf.KeyGroups[0][2].ToString())
```
Comment (jonasbadstuebner) [inline config/config_test.go:557]: I think there should be a test-case where both context and profile are set?

File: kms/keysource.go [hunk 2]
```diff
@@ -278,7 +311,18 @@ func (key *MasterKey) NeedsRotation() bool {
...
-	return key.Arn
+	arnRole := key.Arn
+	if key.Role != "" {
+		arnRole = fmt.Sprintf("%s+%s", key.Arn, key.Role)
+	}
+	context := kmsContextToString(key.EncryptionContext)
+	if key.AwsProfile != "" {
+		return fmt.Sprintf("%s|%s|%s", arnRole, context, key.AwsProfile)
+	}
+	if len(key.EncryptionContext) > 0 {
```
Comment (jonasbadstuebner) [inline kms/keysource.go:322]:
```suggestion
	if context != "" {
```
Just a thought, that the `kmsContextToString` could return something even if the length of the `EncryptionContext` is zero. It doesn’t right now, but maybe in the future?
Checking if the string is empty is also more consistent with the other if statements.

**Review by jonasbadstuebner — CHANGES_REQUESTED** [review]
Hey Felix,
first of all, thank you for creating this fix. Sorry that I broke stuff for others with my change.

The PR looks good to me.
I still am no AWS guy, so my comments on it can not cover the behavior of the code after your changes. I cannot judge if it is working correctly afterwards, but I understood the https://github.com/getsops/sops/issues/1580#issuecomment-2599051188 to match what you implemented now.

:rocket:

File: config/config_test.go (hunk 1 above)
Comment (felixfontein) [reply config/config_test.go:640]: I've added some more tests.

File: kms/keysource.go (hunk 2 above)
Comment (felixfontein) [reply kms/keysource.go]: I don't think `kmsContextToString()` should ever return anything than the empty string for an empty `EncryptionContext`.

**Comment by benlangfeld** [comment]
This fixes my use case, thanks!

/cc @iblackman

**Review by hiddeco — APPROVED** [review]

**Comment by felixfontein** [comment]
@jonasbadstuebner @hiddeco thanks a lot for reviewing this!
