### PR TITLE
pgp: improve handling of GnuPG home dir

### LINKED ISSUE #1294: sops 3.8.0 doesn't work with qubes split gpg
Cross posting from https://github.com/getsops/sops/pull/1054#issuecomment-1722630295

After upgrading to the new release, qubes split gpg (https://www.qubes-os.org/doc/split-gpg/ / https://github.com/QubesOS/qubes-app-linux-split-gpg) is no longer working.
I think this is due to the new release passing `--no-default-keyring` and `--homedir` which are both broken with qubes split gpg for different reasons:
  - `--no-default-keyring` is handled [here](https://github.com/QubesOS/qubes-app-linux-split-gpg/blob/ef64f62a882a2e62f31c06ab5e02cbe7e0dd1643/gpg-client-wrapper#L39-L40)
  - `--homedir` isn't handled at all, and it fails with `qubes-gpg-client: unrecognized option '--homedir'`

Also filed this issue with qubes: https://github.com/QubesOS/qubes-issues/issues/8523

### PR DESCRIPTION
**Pull request by hiddeco**
Fixes #1294

### CODE REVIEW

File: pgp/keysource.go [hunk 1]
```diff
@@ -587,7 +566,7 @@ func fingerprintIndex(ring openpgp.EntityList) map[string]openpgp.Entity {
 // When the command fails, an error is returned.
 func gpgExec(gnuPGHome string, args []string, stdin io.Reader) (err error, stdout bytes.Buffer, stderr bytes.Buffer) {
 	if gnuPGHome != "" {
-		args = append([]string{"--no-default-keyring", "--homedir", gnuPGHome}, args...)
+		args = append([]string{"--homedir", gnuPGHome}, args...)
```
Comment (devstein) [inline pgp/keysource.go:569]: I was confused by this argument name with the same name as new function `gnuPGHome`. Maybe rename to `gnuPGHomeDir`?

File: pgp/keysource.go [hunk 2]
```diff
@@ -318,7 +318,7 @@ func (key *MasterKey) encryptWithGnuPG(dataKey []byte) error {
 		fingerprint,
 		"--no-encrypt-to",
 	}
-	err, stdout, stderr := gpgExec(key.gnuPGHome(), args, bytes.NewReader(dataKey))
+	err, stdout, stderr := gpgExec(key.gnuPGHomeDir, args, bytes.NewReader(dataKey))
```
Comment (devstein) [inline pgp/keysource.go:321]: Just confirming that this shouldn't be:  `gnuPGHome(key.gnuPGHomeDir)`

File: pgp/keysource.go [hunk 3]
```diff
@@ -407,7 +407,7 @@ func (key *MasterKey) decryptWithGnuPG() ([]byte, error) {
 	args := []string{
 		"-d",
 	}
-	err, stdout, stderr := gpgExec(key.gnuPGHome(), args, strings.NewReader(key.EncryptedKey))
+	err, stdout, stderr := gpgExec(key.gnuPGHomeDir, args, strings.NewReader(key.EncryptedKey))
```
Comment (devstein) [inline pgp/keysource.go:410]: Same

File: pgp/keysource.go [hunk 4]
```diff
@@ -609,6 +588,27 @@ func gpgBinary() string {
...
+			usr, err := user.Current()
+			if err != nil {
+				return filepath.Join(os.Getenv("HOME"), ".gnupg")
+			}
+			return filepath.Join(usr.HomeDir, ".gnupg")
+		}
+		return dir
+	}
+	return customPath
+}
```
Comment (devstein) [inline pgp/keysource.go:610]: Nit: Any reason not to use early returns to match the order preference? IMO it improves readability 
```go
func gnuPGHome(customPath string) string {
  if customPath != "" {
    return customPath
  }

  dir := os.Getenv("GNUPGHOME")
  if dir != "" {
    return dir
  }

  usr, err := user.Current()
  if err != nil {
    return filepath.Join(os.Getenv("HOME"), ".gnupg")
  }

  return filepath.Join(usr.HomeDir, ".gnupg")
}
```

**Review by devstein — COMMENTED** [review]
I don't understand the impact of this, but few minor code comments and clarifications

File: pgp/keysource.go (hunk 2 above)
Comment (hiddeco) [reply pgp/keysource.go:321]: It shouldn't, because that would re-introduce the behavior of always supplying a home directory (resulting in `--homedir` getting configured).

File: pgp/keysource.go (hunk 4 above)
Comment (hiddeco) [reply pgp/keysource.go:610]: No particular reason. I am in a weird camp that actually finds the current thing more readable as-is, but that is very subjective :-)

File: pgp/keysource.go (hunk 1 above)
Comment (hiddeco) [reply pgp/keysource.go:569]: Will actually just change it to `homeDir` to match the flag.

**Review by devstein — COMMENTED** [review]
LGTM

**Review by devstein — APPROVED** [review]
