### PR TITLE
Fix Shamir threshold encoding for INI and ENV files

### LINKED ISSUE #837: Shamir is currently broken for INI file types
The resulting error is:
```
json: cannot unmarshal string into Go struct field Metadata.shamir_threshold of type int
```

With the shamir threshold being:
```
shamir_threshold  = 2.000000
```

### PR DESCRIPTION
**Pull request by felixfontein**
Looks like #1394 was inadequate. This fixes it correctly.

Fixes #837.

### CODE REVIEW

File: stores/flatten.go [hunk 1]
```diff
@@ -274,5 +274,11 @@ func EncodeNonStrings(m map[string]interface{}) {
 		if vInt, ok := v.(int); ok {
 			m["shamir_threshold"] = fmt.Sprintf("%d", vInt)
 		}
+		// FlattenMetadata serializes the input as JSON and then deserializes it.
+		// The JSON unserializer treats every number as a float, so the above 'if'
+		// never applies in that situation.
+		if vFloat, ok := v.(float64); ok {
+			m["shamir_threshold"] = fmt.Sprintf("%g", vFloat)
```
Comment (hiddeco) [inline stores/flatten.go:281]: It would probably be safer to do something like: 

```suggestion
			m["shamir_threshold"] = fmt.Sprintf("%.0f", vFloat)
```

The problem is that otherwise `DecodeNonStrings` wouldn't be able to parse e.g. `1234567.0`, as it would become `1.234567e+06`.

Comment (felixfontein) [reply stores/flatten.go]: shamir_threshold should never be that large, but this is still better since it avoids making the result look like a floating point number!

**Review by hiddeco — APPROVED** [review]

**Comment by felixfontein** [comment]
@hiddeco thanks for reviewing!
